openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
  - url: https://jobs-api-06.herokuapp.com/api/v1
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '200':
          description: User is succesfully registered
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          description: User logged in
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
      responses:
        '200':
          description: Job position is created
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      responses:
        '200':
          description: All job positions are received.
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Uniqe job position identifier
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      responses:
        '200':
          description: The job position is succesfullly received
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
      responses:
        '200':
          description: Job position is updated
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      responses:
        '200':
          description: Job position is deleted
components:
  schemas:
    RegisterUserRequest:
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUserRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    CreateJobRequest:
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
    UpdateJobRequest:
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
    description: Authinfication operations (registration and log in).
  - name: Jobs
    description: Manage job positions.

